"""Inspector 状态存储后端抽象（对齐 inspector_state.InspectorState API）。"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Protocol, runtime_checkable


@runtime_checkable
class InspectorStateBackend(Protocol):
    def bind_session(self, session_id: Optional[str]) -> None: ...

    def get_cached_result(self, url: str) -> Optional[Dict[str, Any]]: ...

    def update_state(self, url: str, report: Dict[str, Any]) -> None: ...

    def add_to_remine_queue(self, l2_url: str) -> None: ...

    def get_and_clear_remine_queue(self) -> List[str]: ...

    def get_summary(self) -> Dict[str, int]: ...

    def save_state(self) -> None: ...
