import os
import json
from datetime import datetime
from typing import List, Dict, Any

class MinerReportNode:
    def __init__(self, report_dir: str = None):
        if report_dir is None:
            current_dir = os.path.dirname(os.path.abspath(__file__))
            project_root = os.path.abspath(os.path.join(current_dir, "../../../../"))
            self.report_dir = os.path.join(project_root, "reports", "miner_reports")
        else:
            self.report_dir = report_dir
            
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir, exist_ok=True)

    def generate(self, domain_stats: Dict[str, Any], evolution_dna: Dict[str, Any], all_results: List[Dict]) -> str:
        """
        生成 Miner 专属的深度挖掘报告，包含 L1-L4 等级分布及具体链接明细
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"Miner_Evolution_Report_{timestamp}.md"
        filepath = os.path.join(self.report_dir, filename)

        total_domains = len(domain_stats)
        total_links = len(all_results)
        
        level_counts = {"L1": 0, "L2": 0, "L3": 0, "L4": 0}
        
        # 预处理并排序结果 (L4 优先展示)
        sorted_results = []
        for item in all_results:
            lvl = str(item.get("level") or item.get("tier") or "L3").upper()
            if lvl in level_counts:
                level_counts[lvl] += 1
            else:
                lvl = "UNKNOWN"
            # 补齐必要字段以便后续展示
            sorted_results.append({
                "level": lvl,
                "title": str(item.get("title", "No Title")),
                "url": str(item.get("url", "#"))
            })
            
        # 按照 L4 -> L3 -> L2 -> L1 排序
        rank_order = {"L4": 1, "L3": 2, "L2": 3, "L1": 4, "UNKNOWN": 5}
        sorted_results.sort(key=lambda x: rank_order.get(x["level"], 99))

        report_md = f"""# ⛏️ Miner 深度挖掘与进化报告
**生成时间**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**代际状态**: Gen {evolution_dna.get('generation', evolution_dna.get('gen', 0))}

---

## 📊 资产分级统计 (Clue Hierarchy)
| 等级 | 发现数量 | 处理建议 |
| :--- | :--- | :--- |
| **L1 (枢纽)** | {level_counts['L1']} | 记录入口 |
| **L2 (门户)** | {level_counts['L2']} | 深度扫描 |
| **L3 (数据库)** | {level_counts['L3']} | 核心提取 |
| **L4 (文件/实体)** | {level_counts['L4']} | 直接存储 |

---

## 🧬 进化基因总结 (Evolution DNA)
> 基于本轮运行的反思结果，Miner 已固化/接收以下基因：

* **核心 Prompt 修正**: `{str(evolution_dna.get('user_guidance_prompt', 'N/A'))[:100]}...`
* **当前进化策略**: 已识别 {len(evolution_dna.get('prompt_overrides', {}).get('structure_node', {}).get('add_ignore_patterns', []))} 个过滤模式
* **当前采集深度**: `{evolution_dna.get('max_depth', 2)}`

---

## 🌐 站点挖掘效率分布
| 域名 | 采集数量 | 质量评分 | 状态 |
| :--- | :--- | :--- | :--- |
"""
        for domain, stats in domain_stats.items():
            score = stats.get('score', 0.0)
            status = "✅ 优选" if score >= 0.7 else "⚠️ 低效" if score < 0.3 else "🆗 正常"
            report_md += f"| {domain} | {stats.get('count', 0)} | {score:.2f} | {status} |\n"

        report_md += f"""
---

## 💎 具体资产清单 (Detailed Assets List)
| 层级 | 标题摘要 | 目标链接 |
| :--- | :--- | :--- |
"""
        # 逐条写入资产明细
        for res in sorted_results:
            # 清理标题里的换行符和管道符，防止打断 Markdown 表格
            clean_title = res['title'].replace('\n', ' ').replace('\r', ' ').replace('|', '-')
            # 限制标题长度
            if len(clean_title) > 60:
                clean_title = clean_title[:57] + "..."
            
            report_md += f"| **{res['level']}** | {clean_title} | [访问连接]({res['url']}) |\n"

        report_md += f"""
---

## 📊 统计摘要
* **总扫描域名**: {total_domains} 个
* **总提取资产线索**: {total_links} 条
* **平均站点质量**: {(sum(s.get('score', 0) for s in domain_stats.values()) / total_domains if total_domains > 0 else 0):.2f}

---
*Report generated by MA4CD Miner Node*
"""
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report_md)
        return filepath